name: Terraform CI

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/**'

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
      - name: Terraform fmt
        run: |
          cd terraform
          terraform fmt -check
      - name: Terraform validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate
